defaults: &DEFAULTS
  mailing:
    api_key: key-9hwv5yr-a10nl7gebowlqxvgtiihu4x7
    domain: startmeapps.com
development:
  <<: *DEFAULTS
  host: 192.168.0.167:3000

test:
  <<: *DEFAULTS
  host: test.com

production:
  <<: *DEFAULTS
  host: tell.startmeapps.com
