development:
  adapter: mysql2
  encoding: utf8
  database: tell_development
  pool: 5
  username: root
  password: tincho
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: tell_test
  pool: 5
  username: root
  password: tincho
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: tell_production
  pool: 5
  username: root
  password: tincho
  socket: /var/run/mysqld/mysqld.sock
