# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: "admin@startmeapps.com", username: "admin", password: "1234", admin: true)

Location.create(name: 'ACQUA LOUNGE', address: 'Juana Manso 305 PB', capacity: 214)
Location.create(name: 'AMERIKA', address: 'Gascon 1036', capacity: 2450)
Location.create(name: 'AMNESIA', address: 'Av. Nazca 55', capacity: 778)
Location.create(name: 'ANGEL´S DISCO', address: 'Viamonte 2168', capacity: 425)
Location.create(name: 'ASBURY ROCK', address: 'Rivadavia 7523', capacity: 216)
Location.create(name: 'ASIA DE CUBA', address: 'Olga Cosenttini 751', capacity: 622)
Location.create(name: 'BAHREIN ', address: 'Lavalle 343', capacity: 880)
Location.create(name: 'BELLAKEO NIGHT', address: 'Av. Rivadavia 7428', capacity: 1260)
Location.create(name: 'BOUTIQUE', address: 'Perú 529', capacity: 1950)
Location.create(name: 'BROOK', address: 'Av. Juan B. Justo 1574', capacity: 961)
Location.create(name: 'BRUJAS', address: 'J.L. Borges 1640', capacity: 264)
Location.create(name: 'CAIX', address: 'R. Obligado y Salguero', capacity: 1764)
Location.create(name: 'CASTELBAMBA', address: 'Riobamba 345', capacity: 428)
Location.create(name: 'CATTOS', address: 'Suipacha 930', capacity: 100)
Location.create(name: 'CITY HALL ', address: 'Av. Mosconi 2883', capacity: 1434)
Location.create(name: 'CLOCHE', address: 'J.E. Uriburu 1721', capacity: 588)
Location.create(name: 'CLUB 74', address: 'Figueroa Alcorta 7474', capacity: 180)
Location.create(name: 'CLUB ARÁOZ', address: 'Araoz 2422', capacity: 1030)
Location.create(name: 'CLUB DORADO', address: 'Av. Hipólito Yrigoyen 947', capacity: 400)
Location.create(name: 'CLUB ONE', address: 'Alsina 934', capacity: 1900)
Location.create(name: 'CLUB SHAMPOO', address: 'Quintana 362', capacity: 220)
Location.create(name: 'CONTRAMANO', address: 'Rodiguez Peña 1082 PB', capacity: 335)
Location.create(name: 'CROBAR', address: 'Av. Libertador 3883', capacity: 2258)
Location.create(name: 'DISCO SIX', address: 'Av. Cabildo 3241', capacity: 900)
Location.create(name: 'DOME', address: 'Av. Cabildo 4665', capacity: 1297)
Location.create(name: 'DORSIA', address: 'Alicia Moreau De Justo 2092', capacity: 679)
Location.create(name: 'ECLIPTICO', address: 'Av. Rivadavia 7927', capacity: 743)
Location.create(name: 'EL PICAFLOR', address: 'Av. Corrientes 3530', capacity: 662)
Location.create(name: 'ESPERANTO', address: 'Av. Juan B. Justo 1625', capacity: 572)
Location.create(name: 'EVELYN', address: 'Av. Rivadavia 7425', capacity: 452)
Location.create(name: 'FRODO´S', address: 'Balcarce 605', capacity: 425)
Location.create(name: 'GALLERY', address: 'Azcuenaga 1775 1º', capacity: 254)
Location.create(name: 'GLAM ', address: 'José A. Cabrerea 3046', capacity: 489)
Location.create(name: 'GOLDEN', address: 'Esmeralda 1040', capacity: 408)
Location.create(name: 'GOLF DE PALERMO', address: 'Av. Tornquist 6385', capacity: 950)
Location.create(name: 'GONG', address: 'Av. Córdoba 634', capacity: 100)
Location.create(name: 'GREAT CITY', address: 'Reconquista 876', capacity: 208)
Location.create(name: 'GROOVE', address: 'Av. Santa Fe 4389', capacity: 1685)
Location.create(name: 'INK', address: 'Niceto Vega 5635', capacity: 409)
Location.create(name: 'IVANOFF', address: 'Rivadavia 7514', capacity: 323)
Location.create(name: 'JAGER', address: 'Av. Niceto Vega 5422', capacity: 950)
Location.create(name: 'JANNOY', address: 'Av. Cordoba 2988', capacity: 448)
Location.create(name: 'JET LOUNGE', address: 'Av.Rafael Obligado 4801', capacity: 688)
Location.create(name: 'KIKA', address: 'Honduras 5339', capacity: 1100)
Location.create(name: 'KORY MEGADISCO', address: 'Av. Saenz 459', capacity: 2346)
Location.create(name: 'LA CAPILLA', address: 'Suipacha 842', capacity: 220)
Location.create(name: 'LA CITY', address: 'Av. Alvarez Thomas 1391', capacity: 940)
Location.create(name: 'LA FRANCE', address: 'Sarmiento 1656', capacity: 1372)
Location.create(name: 'LARC', address: 'Av. Niceto Vega 5452', capacity: 980)
Location.create(name: 'LATINO 11', address: 'Ecuador 60', capacity: 1540)
Location.create(name: 'LE CLICK', address: 'Av. Rivadavia 1908', capacity: 990)
Location.create(name: 'LIQUID', address: 'Av. Santa Fé 3651', capacity: 576)
Location.create(name: 'LIV', address: 'Av. Juan B. Justo 1658', capacity: 742)
Location.create(name: 'LO DE CELIA', address: 'Humberto Primo 1783 1°P', capacity: 150)
Location.create(name: 'LOOP', address: 'Av. Beiro 3124', capacity: 247)
Location.create(name: 'LP', address: 'Av. De Mayo 948', capacity: 200)
Location.create(name: 'MÁGICO', address: 'Av. Rivadavia 10925', capacity: 1320)
Location.create(name: 'MAIS- UM', address: 'Av. Juan B. Alberdi 2829', capacity: 504)
Location.create(name: 'MALUCO BELEZA', address: 'Sarmiento 1728', capacity: 1076)
Location.create(name: 'MANDARINE', address: 'R. Obligado y Sarmiento', capacity: 1613)
Location.create(name: 'MBURUCUYA', address: 'Salta 1736', capacity: 1140)
Location.create(name: 'MOD', address: 'Balcarce 563', capacity: 586)
Location.create(name: 'MÓDENA DESIGN', address: 'Figueroa Alcorta 2270', capacity: 581)
Location.create(name: 'MOLIERE', address: 'Balcarce 678', capacity: 819)
Location.create(name: 'MONTECARLO', address: 'Mexico 1861', capacity: 460)
Location.create(name: 'MUNDO LATINO', address: 'Esmeralda 565 P.B.', capacity: 300)
Location.create(name: 'MUSEUM', address: 'Perú 529', capacity: 1952)
Location.create(name: 'NEW PORT', address: 'Junin 1715', capacity: 295)
Location.create(name: 'NICETO CLUB ', address: 'Niceto Vega 5508', capacity: 1118)
Location.create(name: 'ONE MORE', address: 'Av. Beiro 3334', capacity: 480)
Location.create(name: 'OYE CHICO', address: 'Montevideo 306', capacity: 200)
Location.create(name: 'PACHA', address: 'Costanera y Pampa', capacity: 1942)
Location.create(name: 'PAGANA', address: 'Vicente Lopez 2134', capacity: 364)
Location.create(name: 'PALERMO CLUB ', address: 'Borges 2450', capacity: 650)
Location.create(name: 'PHUKET', address: 'Av. La Plata 731', capacity: 1593)
Location.create(name: 'PIZZA BANANA', address: 'Av. Rafael Obligado 6201', capacity: 1143)
Location.create(name: 'PORTO SOHO', address: 'Scalabrini Ortiz 1425', capacity: 604)
Location.create(name: 'POUND', address: 'Av. Sarmiento Y Casares', capacity: 894)
Location.create(name: 'PRIVILEGE BA', address: 'Av. Rafael Obligado 1221', capacity: 2966)
Location.create(name: 'RABBIT', address: 'Av. Scalabrini Ortiz 1648', capacity: 784)
Location.create(name: 'RADIO STUDIO', address: 'O\'brien 1232', capacity: 3050)
Location.create(name: 'RETRO', address: 'Rivadavia 7802', capacity: 1872)
Location.create(name: 'REY CASTRO', address: 'Perú 342', capacity: 901)
Location.create(name: 'ROSEBAR', address: 'Honduras 5445', capacity: 1370)
Location.create(name: 'RUA (CLUB 947)', address: 'Chacabuco 947', capacity: 1702)
Location.create(name: 'SEU DISCO', address: 'Av. Boyaca 28', capacity: 186)
Location.create(name: 'SUDACA', address: 'Sarmiento 1752', capacity: 980)
Location.create(name: 'TABASCO PUB', address: 'José Martí 17', capacity: 999)
Location.create(name: 'TEATRO VORTERIX', address: 'F. Lacroze 3453', capacity: 1584)
Location.create(name: 'TEQUILA', address: 'Av. Rafael Obligado 6211', capacity: 335)
Location.create(name: 'TERRAZAS DEL ESTE', address: 'R. Obligado y Sarmiento', capacity: 3158)
Location.create(name: 'THE FLOWER', address: 'Agüero 445', capacity: 405)
Location.create(name: 'THE SHAMROCK', address: 'Rodriguez Peña 1220', capacity: 396)
Location.create(name: 'THE SUB', address: 'Av. Córdoba 543', capacity: 415)
Location.create(name: 'UGARTE', address: 'Ugarte 1640', capacity: 992)
Location.create(name: 'UNI CLUB', address: 'Guardia Vieja 3360', capacity: 630)
Location.create(name: 'VELVET FRERE', address: 'Olleros 1775', capacity: 650)
Location.create(name: 'VIEJO CORREO', address: 'Av. Diaz Velez 4820', capacity: 300)
Location.create(name: 'VIPER', address: 'Juramento 1531', capacity: 238)
Location.create(name: 'VOODOO MOTEL', address: 'Av. Dorrego 1735', capacity: 187)
Location.create(name: 'VOX(exBED BAIRES)', address: 'Av. Hipoílito Irigoyen 968', capacity: 532)
Location.create(name: 'VRAIE', address: 'Niceto Vega 5681', capacity: 333)
Location.create(name: 'WANNA', address: 'Darwin 1574', capacity: 563)
Location.create(name: 'WESTERN ', address: 'F. Alcorta 7536', capacity: 320)
Location.create(name: 'XEL - HA', address: 'Av. San M Artín 6628', capacity: 692)
Location.create(name: 'YOUR CLUB', address: 'Suipacha 586', capacity: 520)
